CONFIG:
   # activationTime in tick - 20 for 1 second
   activationTime: 18000

MESSAGES:
   Error: "Es ist ein Fehler aufgetreten."
   Help: "Befehlsliste:"
   Invalid_cmd: "Unbekannter Befehl!"
   NoPerms: "Das darfst du nicht tun!"
   Reload: "Xcarts wurde neugeladen."
   Slowdown: "Die Minecarts fahren wieder mit normaler Geschwindigkeit."
   Speedup: "Die Minecarts der Ardabahn fahren nun für 15 Minuten schneller."
   Version: "Aktuelle Version: "

COMMANDS:
   Speedup: "/xcarts speedup"
   Slowdown: "/xcarts slowdown"
   Reload: "/xcarts reload"
   Version: "/xcarts version"

DESCRIPTION:
   Speedup: " - Beschleunigt alle Minecarts der Ardabahn."
   Slowdown: " - Verlangsamt alle Minecarts der Ardabahn."
   Reload: " - Lädt das Plugin neu."
   Version: " - Zeigt Version des Plugins."