CONFIG:
name: XcraftCarts
main: de.xcraft.xcraftcarts.XcraftCarts
version: "1.1.1"
authors:
  - "Sandukhan"
  - "MyNameIsJan"
description: accelerates minecarts past normal speed limits
api-version: 1.18

commands:
   xcarts:
      description: Help Page
      usage: /<command> help
      permission: xcarts.commands

permissions:
  xcarts.commands:
    description: Allows xcarts command
    default: op
